### ISSUE TITLE
[FEATURE-REQUEST] Record just audio

### ISSUE THREAD

**Issue by cinjon** [daily-co/daily-react#14]
How do I record just audio and not the video too? The docs (`https://docs.daily.co/reference/daily-js/instance-methods/start-recording`) show the following command that records video as well. I do *not* want to turn off the displayed video, just not record it.

```
call.startRecording({
  width: 1280,
  height: 720,
  fps: 25,
  backgroundColor: '#FF1F2D3D',
  layout: {
    preset: 'default',
    max_cam_streams: 5,
  },
});
```

**Comment by Regaddi** [comment]
Hey @cinjon,

this sounds like you'll want to record using the [`raw-tracks`](https://docs.daily.co/guides/products/live-streaming-recording/recording-calls-with-the-daily-api#raw-tracks) configuration.
While this might not be _exactly_ what you're asking for, it's the closest Daily is currently offering.

With `raw-tracks` recordings you'll receive individual media tracks in your [custom S3 bucket](https://docs.daily.co/guides/products/live-streaming-recording/storing-recordings-in-a-custom-s3-bucket). From there you'll be able to post-process the audio tracks into a single audio recording.

I'll close this issue for now, as this is a more general question about Daily as a platform and not necessarily a feature request for the Daily React library.

I'd like to invite you to ask similar questions in our [community](https://community.daily.co/) or checkout other questions that were already posted there.

Best,
Christian
