### ISSUE TITLE
Retrieve a recording?

### ISSUE THREAD

**Issue by cinjon** [daily-co/daily-react#17]
A user of mine started a recording but forgot to stop it. It's recording id cdb45f18-63b5-42f2-89e8-0fe111451fa1 - is there any way to retrieve this?

**Comment by cinjon** [comment]
When I try to download this, I get an XML error about the specified key not existing.

**Comment by cinjon** [comment]
Ok, so now the recording seems to be downloading, but it's 2.5gb (I assume because it went for a long time) and it's going to take a long time to download from your servers. Is there a way to cut this down and only download the first 40 mins?

**Comment by Regaddi** [comment]
Hello @cinjon,

I kindly ask you to get in touch with our support team at https://www.daily.co/company/contact/support/ or per mail via help@daily.co.
Issues opened in this repository should have an immediate connection to Daily React.

Closing this issue now, as this isn’t the best place to ask for general support.

Best,
Christian
