### ISSUE TITLE
Error with React 18 in development mode

### ISSUE THREAD

**Issue by TimoBechtel** [daily-co/daily-react#20]
# Expected behavior

Daily works in development mode: The `DailyProvider` manages creating and destroying the callObject correctly.

# Describe the bug (unexpected behavior)

With react 18 running in development mode, it throws the error `Duplicate DailyIframe instances are not allowed`, essentially breaking the app in dev mode. 
This is due to react 18 rendering the app twice in development mode. 

Maybe the call object is not cleaned up correctly on unmount?

# Steps to reproduce

1. Create a react app `npx create-react-app my-app`
3. Replace App.js with the following: 
    ```js
    import { DailyProvider } from '@daily-co/daily-react';
	import './App.css';
	
	function App() {
		return <DailyProvider>Hello World</DailyProvider>;
	}
	
	export default App;
    ```
4. Run the development server `npm start`
5. It now throws the error `Duplicate DailyIframe instances are not allowed`

# System information 

 

* Device:
* OS, version:
* Browser, version:

# Additional context

## Daily versions:

```json
		"@daily-co/daily-js": "0.45.0",
		"@daily-co/daily-react": "^0.8.0",
```

**Comment by Regaddi** [comment]
@TimoBechtel This issue should be fixed in [Daily React 0.9.0](https://github.com/daily-co/daily-react/releases/tag/daily-react-2023-05-25-0.9.0).
Let me know in case you're running into any issues after updating.
