### ISSUE TITLE
Remote screen share track state stuck on "loading" v0.11.0

### ISSUE THREAD

**Issue by troutowicz** [daily-co/daily-react#22]
# Expected behavior

Upon receiving a screen share track, it's video should be visible.

# Describe the bug (unexpected behavior)

A subscribed screen share track is received, but never leaves "loading" state.

# Steps to reproduce

1. User A share screen
2. User B receives
3. User B does not see video due to "loading" state

# System information

* Device: MacBook Air M2
* OS, version: Sonoma (bug exists on other OSs)
* Browser, version: Arc 1.1.1 (bug exists on other browsers)

# Additional context

This issue is not present in v0.10.0. Perhaps a regression with Recoil changes around participants?

**Comment by Regaddi** [comment]
I can confirm that 0.11.2 did not fix this issue, but we've identified the root cause and will work on a fix imminently.

**Comment by Regaddi** [comment]
@troutowicz We've released [0.11.3](https://github.com/daily-co/daily-react/releases/tag/daily-react-2023-08-04-0.11.3) with a fix specifically for `useScreenShare`. This should resolve this issue.

**Comment by troutowicz** [comment]
This seems resolved, but now we're receiving `nill is not defined` when dealing with `participantIds`. `nil` with 2 letter `l`s
