### ISSUE TITLE
`parentEl` in `useCallFrame` should expect `HTMLDivElement | null` type

### ISSUE THREAD

**Issue by ahkhanjani** [daily-co/daily-react#27]
Normally and as shown in the [documentation](https://docs.daily.co/reference/daily-react/use-call-frame), the initial value of `callRef` has to be `null`. So the type of `parentEl` should be like this: `parentEl?: HTMLElement | null`.

**Comment by Regaddi** [comment]
This is fixed in [0.17.1](https://github.com/daily-co/daily-react/releases/tag/daily-react-2024-02-06-0.17.1)
