### ISSUE TITLE
`DailyProvider` should handle `null` call object

### ISSUE THREAD

**Issue by ahkhanjani** [daily-co/daily-react#28]
Currently, `DailyProvider` takes `callObject: DailyCall` as a prop. Both `useCallFrame` and `useCallObject` return `DailyCall | null`. I'm not sure if this is intentional but I expected it to handle the `null` case on its own.

It's not a big deal since a simple `if (!callObject) return;` can fix this but I think this can be a quality of life improvement.

**Edit:** The [documentation](https://docs.daily.co/reference/daily-react/daily-provider) doesn't know about this issue.

**Comment by Regaddi** [comment]
This is fixed in [0.17.1](https://github.com/daily-co/daily-react/releases/tag/daily-react-2024-02-06-0.17.1)
