### ISSUE TITLE
BUG: Infinite recursion in `getParticipantPaths` when using NgZone

### ISSUE THREAD

**Issue by stewartmcgown** [daily-co/daily-react#33]
I have proposed a fix in https://github.com/daily-co/daily-react/pull/34

# Expected behavior

- getParticipantPaths should not infinitely recurse

# Describe the bug (unexpected behavior)

When using React in an Angular controlled application, global objects are monkey-patched with 'zone-aware' properties that Angular uses for change detection. This extends to objects like `MediaStreamTrack`.

`getParticipantPaths` uses a circular-reference unaware check to get nested paths, so it errors out as the zone properties are  infinitely referencing themselves.

**The solution is to make getParticipantPaths aware of circular references and not cause a max call stack error**

# Steps to reproduce

1. Run Daily SDK in an Angular app that has react components mounted
2. Create a call
3. Someone joins the call
4. See maximum call stack exceeded

# Screenshots

![image](https://github.com/daily-co/daily-react/assets/1136276/77d10b8d-2a34-4e8e-a2ef-88bbe67aab22)
> Image of the debugger catching the beginning of the infinite recursion

![image](https://github.com/daily-co/daily-react/assets/1136276/055cd632-1963-4d11-9a87-dce5f49b8fe1)
> Minified error from the getPaths function when a user joins the call

# System information 

 

* Device:
* OS, version:
* Browser, version:

# Additional context

**Comment by mattieruth** [comment]
Thanks for filing the issue and the patch! We're looking into to.

**Comment by Regaddi** [comment]
The fix is included in [0.19.1](https://github.com/daily-co/daily-react/releases/tag/daily-react-2024-06-27-0.19.1).

Thanks for your support, @stewartmcgown!
