### ISSUE TITLE
[FEATURE-REQUEST] Swap from recoil to jotai for state management

### ISSUE THREAD

**Issue by TimHeckel** [daily-co/daily-react#35]
# Feature request

I would like the `@daily-co/daily-react` JavaScript component to switch from Recoil to Jotai for state management, especially in light of the issues observed with Recoil in React 18.

The two have very similar APIs and a half a day of find and replace may be all that's needed in the daily repo. Please consider this!

# Why you need this

Recoil has shown several issues when used with React 18, particularly concerning the new concurrent features and Suspense. These issues include instability in concurrent rendering and difficulties in maintaining consistent behavior with React 18's strict mode. Recoil, while powerful, is still considered an experimental state management library and its API and behavior could change, leading to potential future issues and maintenance burdens.

On the other hand, Jotai provides a simpler and more flexible state management solution that aligns more closely with React's mental model, especially with the changes introduced in React 18. Jotai's minimalistic approach reduces complexity, and it works seamlessly with React's new features, making it more robust and future-proof.

By switching to Jotai, the `@daily-co/daily-react` component can benefit from:

- **Better Compatibility with React 18**: Jotai integrates well with React's latest features, ensuring smoother upgrades and fewer breaking changes in the future.
- **Simplicity and Flexibility**: Jotai's API is simple, with a more React-like approach to state management, which can lead to fewer bugs and easier maintenance.
- **Performance**: Jotai offers excellent performance, especially in large-scale applications where state management complexity can grow over time.

# Alternatives you've considered

Given the issues with Recoil in React 18, I've considered sticking with Recoil and waiting for future updates that might address these problems. However, this approach might lead to ongoing instability and additional workarounds. 

Another alternative could be to use other state management solutions like Zustand or Redux Toolkit, but Jotai stands out for its simplicity, React-first design, and its proven stability with React 18.

# Additional context

Switching to Jotai not only addresses the immediate compatibility concerns with React 18 but also positions the `@daily-co/daily-react` library to be more maintainable and adaptable to future updates in the React ecosystem. Given the trajectory of React's development, aligning the state management library with one that is future-proof and stable will greatly benefit both the maintainers and the users of `@daily-co/daily-react`.

**Comment by jamsea** [comment]
Hi @TimHeckel!

This is on our radar for all the reasons you've outlined. We've recently switched to `jotai` internally for our Daily Prebuilt product. We intend to eventually switch `daily-react` to `jotai` too, we just need to work on other priorities first 👍

**Comment by TimHeckel** [comment]
That's great! I've just updated my own app to use jotai and react 18, but now, unfortunately, I realize I have to install both jotai and recoil for `daily-react` compatibility. I'm sure you're super busy, but is there any ETA on this development work?

**Comment by jamsea** [comment]
Hi @TimHeckel, there’s no ETA at this time, but if you think you’ve identified a path to find/replace this, we’re open to reviewing the pull request! 😁

**Comment by TimHeckel** [comment]
Hi @jamsea  - this is a lot trickier than I thought :) I spent a bunch of time and recoil is completely swapped out for jotai and `npm install --also-dev --legacy-peer-deps` works, but the tests via `npm test` are not passing fully. Perhaps this effort would be enough to kickstart further work on your side? Or if one of your developers could pull this down and run `npm test -- test/hooks/useReceiveSettings.test.tsx` and help shed some light, that would be helpful. Currently It's emitting:

```
 FAIL  test/hooks/useReceiveSettings.test.tsx (5.251 s)
  useReceiveSettings
    ✓ returns base settings and updateReceiveSettings (16 ms)
    ✓ receive-settings-updated event calls provided callback (12 ms)
    ✕ receive-settings-updated event updates returned receiveSettings (base) (1021 ms)
    ✕ receive-settings-updated event updates returned receiveSettings (id) (1007 ms)
    ✕ returns baseSettings in case id is not set (1018 ms)
    ✓ updateReceiveSettings calls daily.updateReceiveSettings, when meeting state is joined-meeting (9 ms)
 ```

But if I could codify some of the patterns with this test, I think it would speed up the rest...

The repo is here:
https://github.com/TimHeckel/daily-react

**Comment by jamsea** [comment]
@TimHeckel the main engineer for Daily React is out of office the rest of the week but I'll loop them in! Thanks!

**Comment by Regaddi** [comment]
Hey @TimHeckel,

thanks a lot for providing the fork and for diving into the work already!
I'm looking into it now and will keep you updated on the progress 👍

**Comment by Regaddi** [comment]
I ran through the changes @TimHeckel provided and fixed a couple of issues. This looks generally good now, I'm waiting for our E2E test suite to run through and will have an internal review of the changes.
Thanks a lot for the work, @TimHeckel!
