### ISSUE TITLE
BUG: fail gracefully when WebRTC disabled

### ISSUE THREAD

**Issue by dwelle** [daily-co/daily-react#37]
# Expected behavior

When user has WebRTC disabled / not supported, the `<DailyProvider/>` and other components such as `<DailyAudio/>` should fail gracefully.

# Describe the bug (unexpected behavior)

Currently it throws on render, bubbling up to the ErrorBoundary with `Uncaught TypeError: Right-hand side of 'instanceof' is not an object`, effectively killing the app.

# Steps to reproduce

Block WebRTC by removing `MediaStreamTrack` from `window` (`window.MediaStreamTrack = null`). Users usually do this as privacy/fingerprinting safety measure by using extensions like https://chromewebstore.google.com/detail/webrtc-control/fjkmabmdepjfammlpliljpnbhleegehm.

# System information 

* `@daily-co/daily-react@0.21.1`
* Browser, version: Chrome 129

**Comment by Regaddi** [comment]
Thank you for the report, @dwelle!
There is a fix for Daily React on main already, which will go out with the next release.
I have also forwarded this issue to my colleagues working on daily-js for investigation.

**Comment by Regaddi** [comment]
Fixed with [0.21.3](https://github.com/daily-co/daily-react/releases/tag/daily-react-2024-10-24-0.21.3)
