### ISSUE TITLE
Allow nested RecoilRoot structure

### ISSUE THREAD

**Issue by zukilover** [daily-co/daily-react#4]
# Feature request
Using daily-react inside an application that uses Recoil will lose its ability to access its state values of the nearest ancestor RecoilRoot.

# Why you need this
We have application set up with Recoil as its dependency. Since daily-react uses Recoil internally, it is nearly impossible share states between nested RecoilRoot.

# Alternatives you've considered
We have tried moving `DailyProvider` further up in the application structure. We don't think this approach is scalable, since daily-react Recoil does not accept any properties for its internal RecoilRoot implementation.

**Comment by Regaddi** [comment]
Hey @zukilover,

thank you for opening this issue and providing a PR along with it!
I'll take a look at #5 and keep you posted about updates.

Best,
Christian

**Comment by Regaddi** [comment]
A fix for this issue landed on main (cd732e9) and will be available with the next release.
Closing this issue as fixed ✅
